// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJKJ6VO2w19wD8er03WJ4iu9wBJ1mt2XU',
    appId: '1:202309907942:web:7a20c4fae2dbd7496e1227',
    messagingSenderId: '202309907942',
    projectId: 'megapay-688ee',
    authDomain: 'megapay-688ee.firebaseapp.com',
    storageBucket: 'megapay-688ee.appspot.com',
    measurementId: 'G-FBHNR72K2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI-45WgSu79PSJgCZVmTwkXP985qZ2P1M',
    appId: '1:202309907942:android:2cf23f8c3a7773226e1227',
    messagingSenderId: '202309907942',
    projectId: 'megapay-688ee',
    storageBucket: 'megapay-688ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgiZ4EP4XZhQRcH7TDHF3OR00i7ihPeCI',
    appId: '1:202309907942:ios:e80e63de005cee9d6e1227',
    messagingSenderId: '202309907942',
    projectId: 'megapay-688ee',
    storageBucket: 'megapay-688ee.appspot.com',
    iosBundleId: 'com.example.megapayNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgiZ4EP4XZhQRcH7TDHF3OR00i7ihPeCI',
    appId: '1:202309907942:ios:e80e63de005cee9d6e1227',
    messagingSenderId: '202309907942',
    projectId: 'megapay-688ee',
    storageBucket: 'megapay-688ee.appspot.com',
    iosBundleId: 'com.example.megapayNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJKJ6VO2w19wD8er03WJ4iu9wBJ1mt2XU',
    appId: '1:202309907942:web:7949ef7159f56f876e1227',
    messagingSenderId: '202309907942',
    projectId: 'megapay-688ee',
    authDomain: 'megapay-688ee.firebaseapp.com',
    storageBucket: 'megapay-688ee.appspot.com',
    measurementId: 'G-2WJ1D113HW',
  );

}